CONNECT system/system;

DROP USER ar CASCADE;

CREATE USER ar IDENTIFIED BY ar DEFAULT TABLESPACE users;

DROP USER joel;

CREATE USER joel IDENTIFIED BY sesame
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

ALTER USER joel QUOTA 10M ON users;
ALTER USER joel QUOTA 0 ON users;

DROP USER john;

CREATE USER john IDENTIFIED BY sesame DEFAULT TABLESPACE users;

ALTER USER john IDENTIFIED BY secret;
ALTER USER john IDENTIFIED BY sesame;
ALTER USER john PASSWORD EXPIRE;

ALTER USER john ACCOUNT LOCK;
ALTER USER john ACCOUNT UNLOCK;