-- How to set the TRANSACTION ISOLATION LEVEL to READ COMMITTED (the default)
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;

-- How to set the TRANSACTION ISOLATION LEVEL to READ SERIALIZABLE
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;